#日志配置
logging:
  level:
    com:
      tony:
        user:DEBUG

# 服务端口号
server:
  port: 8009



# redis 配置
spring:
  redis:
    host:
    port: 6379
    database: 1
    password:
    timeout: 5000
    jedis:
     pool:
       max-active: 50
       max-wait: 3000
       max-idle: 20
       min-idle: 2

  #mysql 配置
  datasource:
    url: jdbc:mysql://:3306/ORDERS?autoReconnect=true&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8
    username: ORDERS
    password: ORDERS
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5

#mybatis 配置
mybatis:
  mapper-locations: classpath*:mybatis/*.xml






